# 定义workflow的名称
name: love-grilfriend

# 指定触发方式
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 0 */12 0'

# 定义job任务列表
jobs:
  # 项目lint检查
  build_job:
    # 指定运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    # 指定具体需要执行步骤和命令
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    # 步骤名称
    - name: Install Dependencies
      # 该步骤运行的命令或者action
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Python Lint
      run: inv lint
    - name: Python Test
      run: |
        pip install pytest
        pytest

  # 报错发送邮件
  send_mail_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v1
    - name: Get Weather
      run: bash ./weather.sh
    - name: Send Mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Xi'an Weather Report
        body: file://result.html
        to: escapehack@gmail.com
        from: GitHub Actions
        content_type: text/html
